### ISSUE TITLE
SyntaxError: Unterminated string in JSON at position 4092

### ISSUE THREAD

**Issue by dimer47** [NilsFa1/bpac-js#6]
Description:
I encountered an issue with the library while running my Node.js program. Occasionally, I receive the following error:

```
SyntaxError: Unterminated string in JSON at position 4092
    at JSON.parse (<anonymous>)
    at new BpacResult (C:\Users\Admin\Desktop\project\node_modules\@nfails\bpac-js\dist\util.js:117:26)
    at Socket.resolveFn (C:\Users\Admin\Desktop\project\node_modules\@nfails\bpac-js\dist\util.js:158:25)
    at Socket.emit (node:events:530:35)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

This error seems to occur randomly, and even wrapping the JSON parsing in a try-catch block does not mitigate the issue. Instead, it halts the execution of my Node.js program altogether.

@NilsFa1 do you have any idea why the error is happening, and if so, could you please help me or suggest a solution? 

Thank you for your assistance

**Comment by NilsFa1** [comment]
Yeah looking at the Error I have an Idea, why the Error 
 could occour. I think it's an error in my Implementation.

Currently the Response is not Text-decoded, so getting a Response with a special Character Like " could result in this Error.

Maybe i can create a Fix tomorrow, if it's the Error.

**Comment by dimer47** [comment]
Thank you for your response ! Indeed, it seems the error is random, possibly linked to a special character in the base64 dataurl of the image. However, I wonder why this error is not caught by a try-catch block. I tried implementing a handler that reinitiates the BMP image creation in case of an exception, but it didn’t work because the exception doesn't seem to be raised. Do you have any idea why this behavior occurs?

If you have the opportunity to address this issue, that would be excellent. I am also available to help if needed.

**Comment by NilsFa1** [comment]
I think my guess was wrong.... From my testing it seems like, that `TextDecoder.decode()` does the same decoding as `buffer.toString("utf-8")`.  But I would like to test this a bit more.

Also I got another guess. The position of the error seems a bit strange. Maybe the data send from the pac-Client component is stripped to 4096 bytes. Do you know if the error alway occur at position 4092?

And can you give me an example how you implemented the try and catch block?

**Comment by dimer47** [comment]
Hello @NilsFa1,

First, I would like to apologize for the response time. I've been quite busy lately and have not been able to respond as I had committed to do in my offer of assistance.

Indeed, I had not paid attention to it before, but after conducting further tests, I confirm that the error still occurs at position 4092, which could indicate an issue with the bpac-client component, as you suggested.

Regarding your request for an example where the code is not caught by a try-catch block, here is a simple example:
```javascript
	/**
	 * @param {String} printer Printer name
	 * @param {String} templateUrl Template URL
	 * @param {Object} data Data to be printed
	 *
	 * @return {Promise<object>}
	 */
	async preview(printer, templateUrl, data = {}) {
		try {
			let filename = path.join(FolderService.TMP_FOLDER, `${uniqId()}.lbx`);

			try {
				let response = await axios.get(templateUrl, {responseType: 'stream'})
				const writer = fs.createWriteStream(filename);
				response.data.pipe(writer);
			} catch (e) {
				throw new Error("Cannot download template file : " + e.message);
			}

			const doc = await BpacDocument.Open(filename);
			await doc.SetPrinter(printer, false);

			for (let key in data) {
				let o = await doc.GetObject(key);
				await o.setText(data[key]);
			}

			let image;
			try {
				image = await doc.GetImageData(ExportType.bexBmp, 0, 0)
			} catch (e) {
				throw e
			}
			await doc.Close();

			return image;
		} catch (e) {
			throw new Error("Cannot generate preview : " + e.message);
		}
	}
```

In the following code, despite the error reported in the image generation via the `GetImageData` method, we do not enter the local case, much less the general catch of my `preview` method. The error interrupts the application directly and displays:
```
SyntaxError: Unterminated string in JSON at position 4092
    at JSON.parse (<anonymous>)
    at new BpacResult (C:\Users\Admin\Desktop\project\node_modules\@nfails\bpac-js\dist\util.js:117:26)
    at Socket.resolveFn (C:\Users\Admin\Desktop\project\node_modules\@nfails\bpac-js\dist\util.js:158:25)
    at Socket.emit (node:events:530:35)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

To give you an overview of how the code that initiates image generation works, I use a WebSocket server that listens for events and triggers image generation using the previously mentioned preview method.

I would like to thank you once again for your help and collaboration in resolving this bug.

Once again, I apologize for the delay in response. I commit to responding more promptly from now on.

Sincerely,
Dimer47

**Comment by NilsFa1** [comment]
Hello @dimer47,

Thank you for the Response. 

I found and fixed the Issue why the Error wasn't catched. The Communication with the bpac Client component runs in a Child Process and the Error was thrown on this one. Now this Error will be thrown on the main process and you will be able to catch it in your Program.

Furthermore I could not reproduce your Error till now. I think I can test this in the next days more.

Still I created a Fix, so if the data is sent in Chunks it will wait for the expected Message length. But I don't know for sure, that this will fix the Error....

**Comment by dimer47** [comment]
Hello @NilsFa1,

Super, thank you very much for investigating and fixing the issue. 

It seems that sending the data in chunks until the complete message is received might resolve the problem. Perhaps sending the data in pieces until the complete message is received will solve the problem. I will test this and confirm if this fixes the issue or not. 
If it doesn't, as a worst-case scenario, now that the errors are caught in the main process, I can implement an automatic retry method with a maximum of three attempts. I will test everything and get back to you.

Thank you once again for your assistance.

**Comment by NilsFa1** [comment]
Hello @dimer47,

did you had you had time to test the bugfix?

Sincerely,
NilsFa

**Comment by dimer47** [comment]
Hello @NilsFa1,

I'm really sorry for the delayed response. I confirm that the applied fix effectively resolves the issue: I encountered no errors during preview generation, despite repeated and successive tests.

Before the fix, one out of four generations would result in an error, but after applying the fix, no errors occurred.

Therefore, I couldn't verify if the error was properly caught in the try/catch block, but in any case, the problem is resolved.

Thank you very much for your help, for the fix, and especially for your responsiveness. Many thanks.

Sincerely,
Dimer47
